// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vector_2_type::DbVector2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Circle {
    pub player_id: __sdk::Identity,
    pub position: DbVector2,
    pub direction: DbVector2,
    pub speed: f32,
}

impl __sdk::InModule for Circle {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Circle`.
///
/// Provides typed access to columns for query building.
pub struct CircleCols {
    pub player_id: __sdk::__query_builder::Col<Circle, __sdk::Identity>,
    pub position: __sdk::__query_builder::Col<Circle, DbVector2>,
    pub direction: __sdk::__query_builder::Col<Circle, DbVector2>,
    pub speed: __sdk::__query_builder::Col<Circle, f32>,
}

impl __sdk::__query_builder::HasCols for Circle {
    type Cols = CircleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CircleCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            direction: __sdk::__query_builder::Col::new(table_name, "direction"),
            speed: __sdk::__query_builder::Col::new(table_name, "speed"),
        }
    }
}

/// Indexed column accessor struct for the table `Circle`.
///
/// Provides typed access to indexed columns for query building.
pub struct CircleIxCols {
    pub player_id: __sdk::__query_builder::IxCol<Circle, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Circle {
    type IxCols = CircleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CircleIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Circle {}
