// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::card_type::Card;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Deck {
    pub game_id: u64,
    pub cards: Vec<Card>,
}

impl __sdk::InModule for Deck {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Deck`.
///
/// Provides typed access to columns for query building.
pub struct DeckCols {
    pub game_id: __sdk::__query_builder::Col<Deck, u64>,
    pub cards: __sdk::__query_builder::Col<Deck, Vec<Card>>,
}

impl __sdk::__query_builder::HasCols for Deck {
    type Cols = DeckCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeckCols {
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            cards: __sdk::__query_builder::Col::new(table_name, "cards"),
        }
    }
}

/// Indexed column accessor struct for the table `Deck`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeckIxCols {
    pub game_id: __sdk::__query_builder::IxCol<Deck, u64>,
}

impl __sdk::__query_builder::HasIxCols for Deck {
    type IxCols = DeckIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeckIxCols {
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Deck {}
