// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::game_state_type::GameState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Game {
    pub id: u64,
    pub state: GameState,
    pub current_seat: u8,
}

impl __sdk::InModule for Game {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Game`.
///
/// Provides typed access to columns for query building.
pub struct GameCols {
    pub id: __sdk::__query_builder::Col<Game, u64>,
    pub state: __sdk::__query_builder::Col<Game, GameState>,
    pub current_seat: __sdk::__query_builder::Col<Game, u8>,
}

impl __sdk::__query_builder::HasCols for Game {
    type Cols = GameCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            current_seat: __sdk::__query_builder::Col::new(table_name, "current_seat"),
        }
    }
}

/// Indexed column accessor struct for the table `Game`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameIxCols {
    pub id: __sdk::__query_builder::IxCol<Game, u64>,
}

impl __sdk::__query_builder::HasIxCols for Game {
    type IxCols = GameIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Game {}
