// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::card_type::Card;
use super::player_hand_type::PlayerHand;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `myhand`.
///
/// Obtain a handle from the [`MyhandTableAccess::myhand`] method on [`super::RemoteTables`],
/// like `ctx.db.myhand()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.myhand().on_insert(...)`.
pub struct MyhandTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerHand>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `myhand`.
pub struct MyhandTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyhandTableAccessor {
    type Row = PlayerHand;
    type Handle<'db> = MyhandTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.myhand()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `myhand`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyhandTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyhandTableHandle`], which mediates access to the table `myhand`.
    fn myhand(&self) -> MyhandTableHandle<'_>;
}

impl MyhandTableAccess for super::RemoteTables {
    fn myhand(&self) -> MyhandTableHandle<'_> {
        MyhandTableHandle {
            imp: self.imp.get_table::<PlayerHand>("myhand"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyhandInsertCallbackId(__sdk::CallbackId);
pub struct MyhandDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyhandTableHandle<'ctx> {
    type Row = PlayerHand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerHand> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyhandTableHandle<'ctx> {
    type Row = PlayerHand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerHand> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyhandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyhandInsertCallbackId {
        MyhandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyhandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyhandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyhandDeleteCallbackId {
        MyhandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyhandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyhandTableHandle<'ctx> {
    type InsertCallbackId = MyhandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyhandInsertCallbackId {
        MyhandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyhandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyhandTableHandle<'ctx> {
    type DeleteCallbackId = MyhandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyhandDeleteCallbackId {
        MyhandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyhandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerHand>("myhand");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerHand>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerHand>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerHand`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait myhandQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerHand`.
    fn myhand(&self) -> __sdk::__query_builder::Table<PlayerHand>;
}

impl myhandQueryTableAccess for __sdk::QueryTableAccessor {
    fn myhand(&self) -> __sdk::__query_builder::Table<PlayerHand> {
        __sdk::__query_builder::Table::new("myhand")
    }
}
