// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlacedBid {
    pub seat_id: u64,
    pub game_id: u64,
    pub bidding_amount: u64,
}

impl __sdk::InModule for PlacedBid {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlacedBid`.
///
/// Provides typed access to columns for query building.
pub struct PlacedBidCols {
    pub seat_id: __sdk::__query_builder::Col<PlacedBid, u64>,
    pub game_id: __sdk::__query_builder::Col<PlacedBid, u64>,
    pub bidding_amount: __sdk::__query_builder::Col<PlacedBid, u64>,
}

impl __sdk::__query_builder::HasCols for PlacedBid {
    type Cols = PlacedBidCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlacedBidCols {
            seat_id: __sdk::__query_builder::Col::new(table_name, "seat_id"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            bidding_amount: __sdk::__query_builder::Col::new(table_name, "bidding_amount"),
        }
    }
}

/// Indexed column accessor struct for the table `PlacedBid`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlacedBidIxCols {
    pub game_id: __sdk::__query_builder::IxCol<PlacedBid, u64>,
    pub seat_id: __sdk::__query_builder::IxCol<PlacedBid, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlacedBid {
    type IxCols = PlacedBidIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlacedBidIxCols {
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
            seat_id: __sdk::__query_builder::IxCol::new(table_name, "seat_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlacedBid {}
