// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::placed_bid_type::PlacedBid;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `placed_bid`.
///
/// Obtain a handle from the [`PlacedBidTableAccess::placed_bid`] method on [`super::RemoteTables`],
/// like `ctx.db.placed_bid()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.placed_bid().on_insert(...)`.
pub struct PlacedBidTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlacedBid>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `placed_bid`.
pub struct PlacedBidTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PlacedBidTableAccessor {
    type Row = PlacedBid;
    type Handle<'db> = PlacedBidTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.placed_bid()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `placed_bid`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlacedBidTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlacedBidTableHandle`], which mediates access to the table `placed_bid`.
    fn placed_bid(&self) -> PlacedBidTableHandle<'_>;
}

impl PlacedBidTableAccess for super::RemoteTables {
    fn placed_bid(&self) -> PlacedBidTableHandle<'_> {
        PlacedBidTableHandle {
            imp: self.imp.get_table::<PlacedBid>("placed_bid"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlacedBidInsertCallbackId(__sdk::CallbackId);
pub struct PlacedBidDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PlacedBidTableHandle<'ctx> {
    type Row = PlacedBid;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlacedBid> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PlacedBidTableHandle<'ctx> {
    type Row = PlacedBid;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlacedBid> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlacedBidInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlacedBidInsertCallbackId {
        PlacedBidInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlacedBidInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlacedBidDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlacedBidDeleteCallbackId {
        PlacedBidDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlacedBidDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PlacedBidTableHandle<'ctx> {
    type InsertCallbackId = PlacedBidInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlacedBidInsertCallbackId {
        PlacedBidInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlacedBidInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PlacedBidTableHandle<'ctx> {
    type DeleteCallbackId = PlacedBidDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlacedBidDeleteCallbackId {
        PlacedBidDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlacedBidDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlacedBidUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlacedBidTableHandle<'ctx> {
    type UpdateCallbackId = PlacedBidUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlacedBidUpdateCallbackId {
        PlacedBidUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlacedBidUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PlacedBidTableHandle<'ctx> {
    type UpdateCallbackId = PlacedBidUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlacedBidUpdateCallbackId {
        PlacedBidUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlacedBidUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `seat_id` unique index on the table `placed_bid`,
/// which allows point queries on the field of the same name
/// via the [`PlacedBidSeatIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.placed_bid().seat_id().find(...)`.
pub struct PlacedBidSeatIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlacedBid, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlacedBidTableHandle<'ctx> {
    /// Get a handle on the `seat_id` unique index on the table `placed_bid`.
    pub fn seat_id(&self) -> PlacedBidSeatIdUnique<'ctx> {
        PlacedBidSeatIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("seat_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlacedBidSeatIdUnique<'ctx> {
    /// Find the subscribed row whose `seat_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlacedBid> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlacedBid>("placed_bid");
    _table.add_unique_constraint::<u64>("seat_id", |row| &row.seat_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlacedBid>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlacedBid>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlacedBid`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait placed_bidQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlacedBid`.
    fn placed_bid(&self) -> __sdk::__query_builder::Table<PlacedBid>;
}

impl placed_bidQueryTableAccess for __sdk::QueryTableAccessor {
    fn placed_bid(&self) -> __sdk::__query_builder::Table<PlacedBid> {
        __sdk::__query_builder::Table::new("placed_bid")
    }
}
