// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlaceBidArgs {
    pub bidding_amount: u64,
}

impl From<PlaceBidArgs> for super::Reducer {
    fn from(args: PlaceBidArgs) -> Self {
        Self::PlaceBid {
            bidding_amount: args.bidding_amount,
        }
    }
}

impl __sdk::InModule for PlaceBidArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_bid`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_bid {
    /// Request that the remote module invoke the reducer `place_bid` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_bid:place_bid_then`] to run a callback after the reducer completes.
    fn place_bid(&self, bidding_amount: u64) -> __sdk::Result<()> {
        self.place_bid_then(bidding_amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `place_bid` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_bid_then(
        &self,
        bidding_amount: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl place_bid for super::RemoteReducers {
    fn place_bid_then(
        &self,
        bidding_amount: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PlaceBidArgs { bidding_amount }, callback)
    }
}
