// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::card_type::Card;
use super::played_card_type::PlayedCard;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `played_card`.
///
/// Obtain a handle from the [`PlayedCardTableAccess::played_card`] method on [`super::RemoteTables`],
/// like `ctx.db.played_card()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.played_card().on_insert(...)`.
pub struct PlayedCardTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayedCard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `played_card`.
pub struct PlayedCardTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PlayedCardTableAccessor {
    type Row = PlayedCard;
    type Handle<'db> = PlayedCardTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.played_card()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `played_card`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayedCardTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayedCardTableHandle`], which mediates access to the table `played_card`.
    fn played_card(&self) -> PlayedCardTableHandle<'_>;
}

impl PlayedCardTableAccess for super::RemoteTables {
    fn played_card(&self) -> PlayedCardTableHandle<'_> {
        PlayedCardTableHandle {
            imp: self.imp.get_table::<PlayedCard>("played_card"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayedCardInsertCallbackId(__sdk::CallbackId);
pub struct PlayedCardDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PlayedCardTableHandle<'ctx> {
    type Row = PlayedCard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayedCard> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PlayedCardTableHandle<'ctx> {
    type Row = PlayedCard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayedCard> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayedCardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayedCardInsertCallbackId {
        PlayedCardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayedCardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayedCardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayedCardDeleteCallbackId {
        PlayedCardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayedCardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PlayedCardTableHandle<'ctx> {
    type InsertCallbackId = PlayedCardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayedCardInsertCallbackId {
        PlayedCardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayedCardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PlayedCardTableHandle<'ctx> {
    type DeleteCallbackId = PlayedCardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayedCardDeleteCallbackId {
        PlayedCardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayedCardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayedCardUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayedCardTableHandle<'ctx> {
    type UpdateCallbackId = PlayedCardUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayedCardUpdateCallbackId {
        PlayedCardUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayedCardUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PlayedCardTableHandle<'ctx> {
    type UpdateCallbackId = PlayedCardUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayedCardUpdateCallbackId {
        PlayedCardUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayedCardUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `played_card`,
/// which allows point queries on the field of the same name
/// via the [`PlayedCardIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.played_card().id().find(...)`.
pub struct PlayedCardIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayedCard, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayedCardTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `played_card`.
    pub fn id(&self) -> PlayedCardIdUnique<'ctx> {
        PlayedCardIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayedCardIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayedCard> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayedCard>("played_card");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayedCard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayedCard>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayedCard`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait played_cardQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayedCard`.
    fn played_card(&self) -> __sdk::__query_builder::Table<PlayedCard>;
}

impl played_cardQueryTableAccess for __sdk::QueryTableAccessor {
    fn played_card(&self) -> __sdk::__query_builder::Table<PlayedCard> {
        __sdk::__query_builder::Table::new("played_card")
    }
}
