// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::card_type::Card;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayedCard {
    pub id: u64,
    pub game_id: u64,
    pub seat_id: u64,
    pub card: Card,
}

impl __sdk::InModule for PlayedCard {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayedCard`.
///
/// Provides typed access to columns for query building.
pub struct PlayedCardCols {
    pub id: __sdk::__query_builder::Col<PlayedCard, u64>,
    pub game_id: __sdk::__query_builder::Col<PlayedCard, u64>,
    pub seat_id: __sdk::__query_builder::Col<PlayedCard, u64>,
    pub card: __sdk::__query_builder::Col<PlayedCard, Card>,
}

impl __sdk::__query_builder::HasCols for PlayedCard {
    type Cols = PlayedCardCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayedCardCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            seat_id: __sdk::__query_builder::Col::new(table_name, "seat_id"),
            card: __sdk::__query_builder::Col::new(table_name, "card"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayedCard`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayedCardIxCols {
    pub game_id: __sdk::__query_builder::IxCol<PlayedCard, u64>,
    pub id: __sdk::__query_builder::IxCol<PlayedCard, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayedCard {
    type IxCols = PlayedCardIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayedCardIxCols {
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayedCard {}
