// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::card_type::Card;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerHand {
    pub seat_id: u64,
    pub player_id: __sdk::Identity,
    pub game_id: u64,
    pub cards: Vec<Card>,
}

impl __sdk::InModule for PlayerHand {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerHand`.
///
/// Provides typed access to columns for query building.
pub struct PlayerHandCols {
    pub seat_id: __sdk::__query_builder::Col<PlayerHand, u64>,
    pub player_id: __sdk::__query_builder::Col<PlayerHand, __sdk::Identity>,
    pub game_id: __sdk::__query_builder::Col<PlayerHand, u64>,
    pub cards: __sdk::__query_builder::Col<PlayerHand, Vec<Card>>,
}

impl __sdk::__query_builder::HasCols for PlayerHand {
    type Cols = PlayerHandCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerHandCols {
            seat_id: __sdk::__query_builder::Col::new(table_name, "seat_id"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            cards: __sdk::__query_builder::Col::new(table_name, "cards"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerHand`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerHandIxCols {
    pub game_id: __sdk::__query_builder::IxCol<PlayerHand, u64>,
    pub player_id: __sdk::__query_builder::IxCol<PlayerHand, __sdk::Identity>,
    pub seat_id: __sdk::__query_builder::IxCol<PlayerHand, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerHand {
    type IxCols = PlayerHandIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerHandIxCols {
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
            seat_id: __sdk::__query_builder::IxCol::new(table_name, "seat_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerHand {}
