// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Seat {
    pub id: u64,
    pub player_id: __sdk::Identity,
    pub game_id: u64,
    pub position: u8,
    pub card_count: u32,
}

impl __sdk::InModule for Seat {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Seat`.
///
/// Provides typed access to columns for query building.
pub struct SeatCols {
    pub id: __sdk::__query_builder::Col<Seat, u64>,
    pub player_id: __sdk::__query_builder::Col<Seat, __sdk::Identity>,
    pub game_id: __sdk::__query_builder::Col<Seat, u64>,
    pub position: __sdk::__query_builder::Col<Seat, u8>,
    pub card_count: __sdk::__query_builder::Col<Seat, u32>,
}

impl __sdk::__query_builder::HasCols for Seat {
    type Cols = SeatCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SeatCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            game_id: __sdk::__query_builder::Col::new(table_name, "game_id"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            card_count: __sdk::__query_builder::Col::new(table_name, "card_count"),
        }
    }
}

/// Indexed column accessor struct for the table `Seat`.
///
/// Provides typed access to indexed columns for query building.
pub struct SeatIxCols {
    pub game_id: __sdk::__query_builder::IxCol<Seat, u64>,
    pub id: __sdk::__query_builder::IxCol<Seat, u64>,
    pub player_id: __sdk::__query_builder::IxCol<Seat, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Seat {
    type IxCols = SeatIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SeatIxCols {
            game_id: __sdk::__query_builder::IxCol::new(table_name, "game_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Seat {}
